### ISSUE TITLE
Delete task not working

### ISSUE THREAD

**Issue by Hasan-git** [aerogear/ionic-showcase#209]
Delete task not updating the cache.

` deleteTask(id: ID!): ID`

should be replaced by 

` deleteTask(id: ID!): Task` 

then fix deleteTask resolver

**Comment by wtrocki** [comment]
💯 Good catch! I think our cache helpers are configured to work with both cases, but we might just have bug somewhere in the app.

**Comment by StephenCoady** [comment]
This bug should be fixed in https://github.com/aerogear/offix/pull/48, specifically: https://github.com/aerogear/offix/pull/48/files#diff-54f1fc59153563ec58bc4ff6964945f1. 

We haven't done full releases yet. Once we do and all dependencies are updated this should go away. There will also be some small updates to the app.

**Comment by wtrocki** [comment]
Fixed
