### ISSUE TITLE
Enable Capacitor

### ISSUE THREAD

**Issue by wtrocki** [aerogear/ionic-showcase#49]
## Motivation

Enabling Ionic Capacitor for Ionic App.
https://capacitor.ionicframework.com/docs/

## Expected outcome

- Providing more native typescript experience for users
- Better integration with Ionic Ecosystem
- Better developer experience
- More flexibility around delivering native functionalities
- More lightweight runtime and build
- Deprecating @aergoear/x-cordova wrappers for plugins 

## Possible actions

- Add Capacitor to Showcase application.
- Verify plugins from showcase app
- Contribute fixes/improvements to Capacitor
- Put your idea here?

## Contact

https://aerogear.org
https://getcapacitor.slack.com
https://twitter.com/wojtroken

**Comment by cjohn001** [comment]
Sounds great,
I am wondering, does aerogear provide a plugin for capacitor for SSO? The only nice solution I found so far is a plugin from ionic for enterprise customers which is not available as open source.
https://ionicframework.com/blog/ionic-auth-connect-single-sign-on-made-easy/

And the alternative solution I came up with so far is via InAppBrowser. But I did not have it on capacitor working yet (cordova only) and it is a pain for ios devices to be set up, because the redirect domain requires a webserver running on a different subdomain than the redirect url as it needs to provide a file with developer credentials in order for the redirect back into the app to work. 

https://medium.com/cofinpro/single-sign-on-mit-cordova-und-keycloak-deb3f250a961

**Comment by wtrocki** [comment]
@cjohn001 Last time I have checked standard keycloak.js was working with capacitor using default adapter. Using cordova adapter will also work but it will require installing InAppBrowser plugin from cordova or mapping `cordova.InAppBrowser.open` to capacitor `Browser.open`.

All depenends on auth flow you would like to implement etc. 
If you reach us on chat we can provide more details or even add capacitor to this repository

**Comment by wtrocki** [comment]
Closed issue as it it very generic for the moment. 
We need individual elements on roadmap for:
- Push
- Sync/Offix (document network adapter)
Tracked in: https://github.com/aerogear/offix/issues/309
- Keycloak - we need more info as on very basic scenarios js adapter will work.

**Comment by wtrocki** [comment]
@secondsun For push roadmap
